import Add from './add.js'
import ArrowSolid from './arrow-solid.js'
import Arrow from './arrow.js'
import Delete from './delete.js'
import Edit from './edit.js'
import GearOption from './gear-option.js'
import Home from './home.js'
import Image from './image.js'
import News from './news.js'
import Padlock from './padlock.js'
import Play from './play.js'
import ProfileUser from './profile-user.js'
import User from './user.js'
import Warning from './warning.js'

export { Add, ArrowSolid, Arrow, Delete, Edit, GearOption, Home, Image, News, Padlock, Play, ProfileUser, User, Warning }
